spring:
  messages:
    basename: i18n.login
  thymeleaf:
    #j禁用缓存
    cache: false
  mvc:
    date-format: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    context-path: /


